  
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laptop
 */
public class Kelola extends javax.swing.JFrame {

    /**
     * Creates new form Kelola
     */
    File file;
    String alamat;
    BufferedReader baca;
    BufferedWriter tulis;
    DefaultTableModel model;
    String no,nm,mrk,hrg,stock;
    public Kelola() {
        initComponents();
        model=(DefaultTableModel)tabelPersediaan.getModel();
        loadData();
        nomorUP.setEnabled(false);
        namaUP.setEnabled(false);
        merekUP.setEnabled(false);
    }
    public void loadData(){
        model.getDataVector().removeAllElements();
        String path = "src/Data/daftarBarang.txt";
        File file = new  File(path);
        try {
            baca = new BufferedReader(new FileReader(file));
            Object[] dataBaris = baca.lines().toArray();
            for(int i=0;i<dataBaris.length;i++){
                String baris = dataBaris[i].toString();
                String[] data = baris.split("/");
                model.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    public void UpdateTxt(){
        alamat = "src/Data/daftarBarang.txt";
        file = new File(alamat);
        try {
            tulis = new BufferedWriter(new FileWriter(file));
            for(int i=0;i<tabelPersediaan.getRowCount();i++){
                for(int j=0;j<tabelPersediaan.getColumnCount();j++){
                    if(j>0)
                        tulis.write("/");
                    tulis.write(tabelPersediaan.getValueAt(i, j).toString());
                }
                tulis.newLine();
            }
            tulis.close();
        } catch (Exception e) {
        }
        loadData();
    }
    public void TambahTbl(){
        no = nomorTB.getText();
        nm = namaTB.getText();
        mrk = merekTB.getText();
        hrg = hargaTB.getText();
        stock = stockTB.getText();
        Object [] data = new Object[5];
        data[0]= no;
        data[1] = nm;
        data[2] = mrk;
        data[3] = hrg;
        data[4] = stock;
        if(nomorTB.getText().isEmpty()||stockTB.getText().isEmpty()||hargaTB.getText().isEmpty()
                ||merekTB.getText().isEmpty()||namaTB.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Harus diisi");
        else{
           model.addRow(data);
           UpdateTxt();
            nomorTB.setText("");
            namaTB.setText("");
            merekTB.setText("");
            hargaTB.setText("");
            stockTB.setText("");
        }
    }
    public void Hapus(){
        int baris = tabelPersediaan.getSelectedRow();
        model.removeRow(baris);
        UpdateTxt();
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    }
    
    public void Update(){
        int barisUP = tabelPersediaan.getSelectedRow();
        hrg = hargaUP.getText();
        stock = stockUP.getText();
        Object [] data = new Object[5];
        data[3] = hrg;
        data[4] = stock;
        model.setValueAt(data[3], barisUP, 3);
        model.setValueAt(data[4], barisUP, 4);
        UpdateTxt();
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nomorTB = new javax.swing.JTextField();
        namaTB = new javax.swing.JTextField();
        merekTB = new javax.swing.JTextField();
        hargaTB = new javax.swing.JTextField();
        stockTB = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        hargaUP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        stockUP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nomorUP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        namaUP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        merekUP = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPersediaan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 68, 90));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cooltext323059585578516.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 30, 570, 60);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseReleased(evt);
            }
        });

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 65, 94, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Merek");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 112, 42, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Harga");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 156, 42, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Stock");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 199, 39, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nomor");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 20, 48, 17);
        jPanel3.add(nomorTB);
        nomorTB.setBounds(110, 20, 187, 30);
        jPanel3.add(namaTB);
        namaTB.setBounds(110, 60, 187, 30);

        merekTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekTBActionPerformed(evt);
            }
        });
        jPanel3.add(merekTB);
        merekTB.setBounds(110, 110, 187, 30);
        jPanel3.add(hargaTB);
        hargaTB.setBounds(110, 150, 187, 30);
        jPanel3.add(stockTB);
        stockTB.setBounds(110, 190, 187, 30);

        jToggleButton2.setText("Tambah Barang");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton2);
        jToggleButton2.setBounds(80, 250, 120, 23);

        jTabbedPane1.addTab("Tambah", jPanel3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pilih baris barang yang ingin di hapus");

        jToggleButton1.setText("Hapus");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Hapus", jPanel2);

        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Harga");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(10, 156, 42, 17);
        jPanel5.add(hargaUP);
        hargaUP.setBounds(110, 150, 187, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Stock");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 199, 39, 17);
        jPanel5.add(stockUP);
        stockUP.setBounds(110, 190, 187, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Pilih baris yang ingin diupdate");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(40, 0, 204, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Nomor");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 30, 48, 17);
        jPanel5.add(nomorUP);
        nomorUP.setBounds(110, 30, 187, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Nama Barang");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 70, 94, 17);
        jPanel5.add(namaUP);
        namaUP.setBounds(110, 70, 187, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Merek");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 112, 42, 17);

        merekUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merekUPActionPerformed(evt);
            }
        });
        jPanel5.add(merekUP);
        merekUP.setBounds(110, 110, 187, 30);

        jToggleButton3.setText("Update");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton3);
        jToggleButton3.setBounds(90, 240, 120, 30);

        jTabbedPane1.addTab("Update Persediaan", jPanel5);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(50, 150, 310, 310);

        tabelPersediaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama Barang", "Merek", "Harga", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelPersediaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelPersediaanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPersediaan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(390, 170, 480, 390);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Persediaan :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 130, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/previous.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(70, 560, 60, 80);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Kembali");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(70, 520, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void merekTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merekTBActionPerformed

    private void merekUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merekUPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merekUPActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        TambahTbl();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Hapus();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTabbedPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseReleased

    }//GEN-LAST:event_jTabbedPane1MouseReleased

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        Welcome wel = new Welcome();
        wel.setVisible(true);
        wel.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void tabelPersediaanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPersediaanMouseReleased
        int larik1 = tabelPersediaan.getSelectedRow();
        nomorUP.setText(""+model.getValueAt(larik1, 0).toString());
        namaUP.setText(""+model.getValueAt(larik1, 1).toString());
        merekUP.setText(""+model.getValueAt(larik1, 2).toString());
        hargaUP.setText(""+model.getValueAt(larik1, 3).toString());
        stockUP.setText(""+model.getValueAt(larik1, 4).toString());
    }//GEN-LAST:event_tabelPersediaanMouseReleased

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        Update();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kelola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kelola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaTB;
    private javax.swing.JTextField hargaUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField merekTB;
    private javax.swing.JTextField merekUP;
    private javax.swing.JTextField namaTB;
    private javax.swing.JTextField namaUP;
    private javax.swing.JTextField nomorTB;
    private javax.swing.JTextField nomorUP;
    private javax.swing.JTextField stockTB;
    private javax.swing.JTextField stockUP;
    private javax.swing.JTable tabelPersediaan;
    // End of variables declaration//GEN-END:variables
}
