/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template fileStok, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author ASUS
 */
public class Utama extends javax.swing.JFrame {

    /**
     * Creates new form Utama
     */
    String alamatStok;
    String psnan, hrg, jml;
    File fileStok;
    BufferedReader baca;
    BufferedWriter tulisStok;
    DefaultTableModel model;
    DefaultTableModel troli;
    String [] data, keranjang;
    //int total=0;
    public Utama() {
        initComponents();
        pesanan.setEnabled(true);
        hargaBarang.setEnabled(true);
        pemesan.setEnabled(true);
        psnan =pesanan.getText();
        hrg=hargaBarang.getText();
        jml=jumlah.getText();
        model=(DefaultTableModel)tabel.getModel();
        troli=(DefaultTableModel)tabelPesan.getModel();
        loadData();
        
    }
    public void Update(){
        alamatStok = "src/Data/daftarBarang.txt";
        fileStok = new File(alamatStok);
        try {
            tulisStok = new BufferedWriter(new FileWriter(fileStok));
            for(int i=0;i<tabel.getRowCount();i++){
                for(int j=0;j<tabel.getColumnCount();j++){
                    if(j>0)
                        tulisStok.write("/");
                    tulisStok.write(tabel.getValueAt(i, j).toString());
                }
                tulisStok.newLine();
            }
            tulisStok.close();
        } catch (Exception e) {
        }
    }
    public void loadData(){
        model.getDataVector().removeAllElements();
        String path = "src/Data/daftarBarang.txt";
        File file = new  File(path);
        try {
            baca = new BufferedReader(new FileReader(file));
            Object[] dataBaris = baca.lines().toArray();
            for(int i=0;i<dataBaris.length;i++){
                String baris = dataBaris[i].toString();
                String[] data = baris.split("/");
                model.addRow(data);
            }
        } catch (Exception e) {
        }
//        alamatStok = "src/Databarang/daftarBarang.txt";
//        fileStok = new File(alamatStok);
//        try {
//            baca = new BufferedReader(new FileReader(fileStok));
//            String barisPertama = baca.readLine();
//            String[] namaKolom = barisPertama.split(",");
//            model = (DefaultTableModel)tabel.getModel();
//            model.setColumnIdentifiers(namaKolom);
//            
//            Object[] dataBaris = baca.lines().toArray();
//            for (int i = 0; i < dataBaris.length; i++){
//                String baris = dataBaris[i].toString();
//                String[] data = baris.split("/");
//                model.addRow(data);
//            }
//        } catch (Exception e) {
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        pemesan = new javax.swing.JTextField();
        pesanan = new javax.swing.JTextField();
        hargaBarang = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPesan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        hargaTotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 720));
        setPreferredSize(new java.awt.Dimension(920, 715));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 68, 90));
        jPanel1.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nama Barang", "Merek", "Harga", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 150, 500, 320);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cooltext323059585578516.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 30, 570, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pemesan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pesanan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah");

        jToggleButton1.setText("Masukkan Troli");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 150, 290, 270);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Daftar Barang dan Harga");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 110, 410, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bayar !");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 480, 100, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/rsz_2kasir.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 520, 150, 140);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Troli Anda :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 480, 170, 30);

        panelTabel.setLayout(null);

        tabelPesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pesanan", "Harga", "Jumlah", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPesan);

        panelTabel.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 500, 150);

        jPanel1.add(panelTabel);
        panelTabel.setBounds(350, 510, 500, 150);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 520, 70, 20);

        hargaTotal.setBackground(new java.awt.Color(255, 255, 255));
        hargaTotal.setOpaque(true);
        jPanel1.add(hargaTotal);
        hargaTotal.setBounds(190, 550, 150, 20);

        jButton1.setText("Batalkan Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(223, 630, 120, 23);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(770, 100, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseReleased
        int larik = tabel.getSelectedRow();
        pesanan.setText(""+model.getValueAt(larik, 2).toString());
        hargaBarang.setText(""+model.getValueAt(larik, 3).toString());
    }//GEN-LAST:event_tabelMouseReleased

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int jml = Integer.parseInt(jumlah.getText());
        String namaProduk="";
        String[] data = new String[4];//array untuk dimasukan ke jTabel2
        boolean ready = false;//status kode barang tersedia di jtble1
        int stok = 0;
        int baris =0;
        int harga = 0;
        for(int i=0;i<tabel.getRowCount();i++){
            if(pesanan.getText().equals(model.getValueAt(i, 1))){
                namaProduk = model.getValueAt(i, 1).toString();
                harga = Integer.parseInt(model.getValueAt(i, 3).toString());
                stok = Integer.parseInt(model.getValueAt(i, 4).toString());
                baris = i;//kode di temukan pada baris ke-i
                ready = true;//bernilai true karena kode tersedia di jtble1
                break;
            }
        }
        if(ready && stok>=jml){
            stok-=jml;//stok = stok-jumlah
            model.setValueAt(stok, baris, 4);//nilai stok berubah pada jtable1
            Update();//update notepad
            loadData();//refresh jtable1
            
            data[0] = namaProduk;
            data[1] = ""+harga;
            data[2] = ""+jml;
            data[3] =""+(harga*jml);
            //tabelPesan.setModel(troli);
            //troli.addRow(data);
            
            Total();
        }else{
            JOptionPane.showMessageDialog(null, "Stok Kosong");
        }
        pesanan.setText("");
        hargaBarang.setText("");
        jumlah.setText("");
//        tulisPesanan();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total=Integer.parseInt(hargaTotal.getText());
        int baris=tabelPesan.getSelectedRow();
        int hargaItem=Integer.parseInt(tabelPesan.getValueAt(baris,3).toString());
        int totalAkhir=total-hargaItem;
        troli.removeRow(baris);
        hargaTotal.setText(""+totalAkhir);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        String pembeli, total;
        pembeli=pemesan.getText();
        total=hargaTotal.getText();
        Pembayaran pembayaran = new Pembayaran(pembeli,total);
        pembayaran.setVisible(true);
        pembayaran.setLocationRelativeTo(null);
        this.dispose();
//        String pembeli, total;
//        pembeli=pemesan.getText();
//        total=hargaTotal.getText();
//        Tagihan tagihan = new Tagihan();
//        tagihan.setVisible(true);
//        tagihan.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Welcome wel = new Welcome();
        wel.setVisible(true);
        wel.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Total(){
        int total=0;
        int [] sub = new int[tabelPesan.getRowCount()];
        for (int i=0; i<tabelPesan.getRowCount();i++){
            sub[i]=Integer.parseInt(tabelPesan.getValueAt(i,3).toString());
            total+=sub[i];
        }
        hargaTotal.setText(""+total);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaBarang;
    private javax.swing.JLabel hargaTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JTextField pemesan;
    private javax.swing.JTextField pesanan;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabelPesan;
    // End of variables declaration//GEN-END:variables
}
